### ISSUE TITLE
Implementation of project

### ISSUE THREAD

**Issue by PWagner1** [kpreisser/TaskDialog#2]
Hi @kpreisser 

I'm the co-creator and owner of the `Krypton .NET 5.4xx` repositories. I came across your repository while looking at the `winforms` repo. I was wondering if it was possible to use your code in my project, which you can find [here](https://github.com/Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470), but using the custom toolkit controls?

Of course I will give you credit for your work.

**Comment by kpreisser** [comment]
Hi,
yes, you can use the code in your project.
Thanks!

**Comment by PWagner1** [comment]
Hi @kpreisser 

Thanks for your response.
